name: Update YouTube Stats
on:
  schedule:
    - cron: '0 12 * * *'  # Runs at noon every day
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests
    - name: Fetch YouTube Stats and Update README
      env:
        API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        CHANNEL_ID: 'UCjf4X2qXcTHa7KoN3m7VKCg'
      run: python fetch_youtube_stats.py
    - name: Commit and Push changes
      run: |
        git config --global user.name 'Your GitHub Username'
        git config --global user.email 'your_email@example.com'
        git add README.md
        git commit -m "Update YouTube Stats" || echo "No changes to commit"
        git push
        
